# -*- coding: utf-8 -*-
"""tasks.py

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/19vUvN8UZpm6LuB0KHohlx0JHtbMWIZRV
"""

import json
import os

FILE = "tasks.json"


def load_tasks():

    # Load tasks from JSON file
    if not os.path.exists(FILE):
        return []

    try:
        with open(FILE, "r", encoding="utf-8") as file:
            return json.load(file)
    except json.JSONDecodeError:
        return []


tasks = load_tasks()


def save_tasks(tasks):

    # Save tasks to JSON file
    with open(FILE, "w", encoding="utf-8") as file:
        json.dump(tasks, file, indent=4)


def add_task():

    # Add a new task
    title = input("Enter task description: ").strip()

    if not title:

        print("Task cannot be empty.")
        return

    task = {"title": title, "done": False}
    tasks.append(task)
    save_tasks(tasks)
    print("Task added successfully.")


def list_tasks():

    # Display all tasks
    if not tasks:
        print("No tasks found.")
        return

    print("\n                 ******Tasks******                 ")
    print("+----+--------+----------------------------------+")
    print("| N° | Status |         Task Title               |")
    print("+----+--------+----------------------------------+")
    for i, task in enumerate(tasks, start=1):
        status = "✓" if task["done"] else "✗"
        print(f"| {i}  |   {status}    | {task['title']}")
        print("+----+--------+----------------------------------+")


def mark_task_done():

    # Mark a task as done
    list_tasks()  # We should display only the undone tasks
    if not tasks:
        return

    while True:
        user_input = input("Enter task number: ").strip()

        try:
            index = int(user_input) - 1
            if 0 <= index < len(tasks):
                tasks[index]["done"] = True
                save_tasks(tasks)
                print("Task marked as done.")
                break
            else:
                print("Invalid task number. Try again.")
        except ValueError:
            print("Please enter a valid number.")


def delete_task():

    # Delete an existed task
    if not tasks:
        return

    list_tasks()
    while True:
        user_input = input("Enter task number: ").strip()

        try:
            index = int(user_input) - 1

            if index >= 0 and index < len(tasks):

                del tasks[index]
                save_tasks(tasks)
                print("Task deleted Successfully.")
                break
            else:
                print("Invalid task number. Try again.")

        except ValueError:
            print("Please enter a valid number.")


def main():

    while True:
        print("\n+---- Task Manager ----+")
        print("| 1. Add new task      |")
        print("| 2. View all tasks    |")
        print("| 3. Mark task as done |")
        print("| 4. Delete task       |")
        print("| 5. Exit              |")
        print("+----------------------+")

        choice = input("Choose an option: ").strip()

        if choice == "1":
            add_task()
        elif choice == "2":
            list_tasks()
        elif choice == "3":
            mark_task_done()
        elif choice == "4":
            delete_task()
        elif choice == "5":
            print("See you next time!")
            break
        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main()
